version: "3.9"
services:
  rabbit-broker:
    image: rabbitmq:3-management-alpine
    container_name: rabbit-broker
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ${HOME}/repos/rabbitmq-data/data/:/var/lib/rabbitmq
      - ${HOME}/repos/rabbitmq-data/log/:/var/log/rabbitmq
    networks:
      - dev-network
  postgres:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ${HOME}/repos/postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dev-network
  api:
    build: .
    restart: on-failure
    depends_on:
      - postgres
      - rabbit-broker
    ports:
      - "8080:8080"
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge